---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
      - resources/lang/
    config:
      languages:
        - ruby
        - javascript
        - python
        - php
  eslint:
    enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
    - "**.css"
    - "**.inc"
    - "**.js"
    - "**.jsx"
    - "**.module"
    - "**.php"
    - "**.py"
    - "**.rb"
exclude_paths:
  - bootstrap/
  - config/
  - database/
  - public/build/
  - tests/
